services:

  nginx:
    container_name: nginxphp
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/public_html
    networks:
      - phpapp
    depends_on:
      - phpfpm
      - mysql

  phpfpm:
    container_name: phpfpm
    build: ./images/php
    volumes:
      - ./app:/var/www/public_html
    networks:
      - phpapp
    depends_on:
      - mysql
    
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql   
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: project
    networks:
      - phpapp

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql
    networks:
      - phpapp
    depends_on:
      - mysql

networks:
  phpapp: 
    name: phpapp